### ISSUE TITLE
The installation instructions make it look like it functions OOTB.

### ISSUE THREAD

**Issue by jamesbt365** [flathub/net.opentabletdriver.OpenTabletDriver#19]
The package does not set up udev rules or blacklisting the kernel drivers, however, the installation guide provides no mention of this.

We have received multiple reports of the flatpak complaining that it doesn't work and it isn't clear how you're supposed to make it work.

You should provide information on how to setup udev rules alongside the kernel level blacklist, and also provide information that this will stop the tablet working without OTD running.

As it stands this is nothing more than a maintenance nightmare for OpenTabletDriver and this package provides little to no benefit for most users as it doesn't provide a seemless installation, this should probably be noted somewhere that if possible users should use official releases.

**Comment by first-storm** [comment]
https://github.com/flathub/net.opentabletdriver.OpenTabletDriver/pull/21

**Comment by first-storm** [comment]
Finished.

**Comment by first-storm** [comment]
I'm very sorry that my readme.md was generated by ChatGPT. I previously noticed that the official OpenTabletDriver website mentioned a solution, so I overlooked this. I am truly sorry.
