### ISSUE TITLE
Please stop blindly copy-pasting OpenTabletDriver docs & responses from ChatGPT.

### ISSUE THREAD

**Issue by jamesbt365** [flathub/net.opentabletdriver.OpenTabletDriver#22]
It was clear from your original PR with this package that something was going on with you mentioning files and architectures that had been deprecated for 1+ year, for the sake of the users using this package, _**please**_ consider at least fact checking and proof reading what you are committing to this repository.

It it is exceedingly clear that you have copy pasted from OTD docs and ChatGPT in multiple places, and failed to format the pre-installation instructions in a manner that makes sense, alongside poorly checking your scripts for anything that doesn't make sense after you copied them. 

You have blindly copy pasted OpenTabletDriver docs [here](https://github.com/flathub/net.opentabletdriver.OpenTabletDriver/blob/78c91eacab3e2e128a333dfbdf80e3bc1e7f7c91/Pre-installation.md#12--for-non-fhs-distronon-fhs-distro), it doesn't even make sense where it is as it goes from *installing* blacklists to *uninstalling* blacklists?

Please adapt our official documentation properly or write docs in a way that make sense to the context they are in, the nonsensical context switches in the middle of documentation is confusing to users and simply stealing parts that do not make sense will not help them in any way, 

Everything I have currently mentioned is a major problem, and the documentation you have provided needs a major refactor as it currently stands, please [request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from one of us in the future when you are providing essential documentation, you are currently incorrectly providing instructions.

[Another part of the docs](https://github.com/flathub/net.opentabletdriver.OpenTabletDriver/blob/78c91eacab3e2e128a333dfbdf80e3bc1e7f7c91/Pre-installation.md#12--for-non-fhs-distronon-fhs-distro) which have been fumbled is here, where you generate the rules for no reason at all, not piping the output into the file or writing it anywhere, this is unnecessary and can be combined which the section below it, where it generates the rules for a second time and pipes the output into the correct location.

I'm also not sure i like the `start-otd.sh` script, but I'm not sure with the flatpak norms and how the rest of the package works, I'll investigate that in my own time.

#### You have poorly worded the mentions to the pre-installation [here](https://github.com/flathub/net.opentabletdriver.OpenTabletDriver/tree/e40d5923982dc9731ea685baf007663fe786680b?tab=readme-ov-file#prerequisites):
> Before installing OpenTabletDriver, you need to set up Flatpak on your system. Follow the [pre-installation guide provided](https://github.com/flathub/net.opentabletdriver.OpenTabletDriver/blob/docs/Pre-installation.md).

It should likely be adapted to reflect what its actually doing, systemwide permission changes to allow the function of the driver, not the setup of flatpak as a whole, that is mentioned in the next section, its redundant to mention it twice and its unclear what the setup is actually doing. 

#### Running scripts with `sudo` despite elevating permissions inside the scripts.
This is typically unnecessary, and also bad practice, you do not need to do both, just elevate in the script, no need to pipe into an elevated bash session.

#### Please do not close this issue until everything here has been fixed appropriately.

Please do not close this issue until everything here has been amended in relevant PRs that have been reviewed by me, or other OpenTabletDriver developers. If you are providing a package that can be used on almost any distro then please, take care of the package instead of carelessly copying or writing docs, you are actively harming the user experience this way and we have had countless individuals complaining about incomplete experience this package provides, we are the only ones currently tanking the maintenance burden that this package currently is.

**Comment by first-storm** [comment]
By the way. Should I remove the step to regenerate initramfs in uninstallation script? Or run it just after delete the modprobe config? I am a little bit confused. Secondly, what should the part in the document about setting up flatpak be like? I will fix the issue you mentioned in the document in a couple of weeks. And thanks for your patience. @jamesbt365

**Comment by jamesbt365** [comment]
I think its mostly done, will close now and reopen with any other concerns I have.
